version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinchos
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    ports:
      - "5100:5100"
    volumes:
      - ./instance:/app/backend/app/instance  # Para que se persista la DB en local
    networks:
      - app-network
  postgresql:
    

networks:
  app-network:
    driver: bridge
