version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinchos
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    ports:
      - "5200:5200"
    volumes:
      - ./instance:/app/backend/app/instance 
    networks:
      - app-network
    depends_on:
      - tinchos_db

  tinchos_db:
    image: postgres:16
    container_name: tinchos_postgresdb
    restart: always 
    env_file:
      - ./backend/.env.prod
    environment:
      POSTGRES_USER: tinchosroot
      POSTGRES_PASSWORD: tinchosweb
      POSTGRES_DB: tinchos
    volumes:
      - tinchos_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  tinchos_pgdata:
    driver: local
